/**
 * Basket helpers — copy lists and open supermarket search pages.
 */

export function buildSearchUrl(supermarket, productName) {
  const query = encodeURIComponent(productName);
  return supermarket.searchUrl.replace('{query}', query);
}

export function formatListForStore(items, supermarket) {
  const header = `Shopping list for ${supermarket.name}\n${'─'.repeat(40)}\n`;
  const lines = items.map((item, index) => `${index + 1}. ${item.name} × ${item.quantity}`);
  const footer = `\n${'─'.repeat(40)}\nGenerated by Supermarket Dash`;
  return header + lines.join('\n') + footer;
}

export function getBasketStrategy(supermarket) {
  const strategies = {
    partial: {
      label: 'Copy & search',
      steps: [
        'Copy your formatted list to clipboard',
        'Open the supermarket website',
        'Search each item and add to basket manually',
        'Use our quick-search links to jump straight to each product',
      ],
    },
    manual: {
      label: 'In-store list',
      steps: [
        'Copy or print your shopping list',
        'Visit the store in person',
        'Aldi and Lidl have limited online grocery — in-store is fastest',
      ],
    },
  };

  return strategies[supermarket.basketAutomation] ?? strategies.partial;
}

export async function copyToClipboard(text) {
  if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return true;
  }

  if (typeof document === 'undefined') {
    return false;
  }

  const textarea = document.createElement('textarea');
  textarea.value = text;
  textarea.style.position = 'fixed';
  textarea.style.opacity = '0';
  document.body.appendChild(textarea);
  textarea.select();
  const ok = document.execCommand('copy');
  document.body.removeChild(textarea);
  return ok;
}

export function openStoreWithFirstItem(supermarket, items) {
  if (!items.length || typeof window === 'undefined') {
    return;
  }
  const url = buildSearchUrl(supermarket, items[0].name);
  window.open(url, '_blank', 'noopener');
}

export function getQuickSearchLinks(supermarket, items) {
  return items.map((item) => ({
    name: item.name,
    quantity: item.quantity,
    url: buildSearchUrl(supermarket, item.name),
  }));
}
